### ISSUE TITLE
Building fails with "Failed to notify ProjectEvaluationListener.afterEvaluate()"

### ISSUE THREAD

**Issue by varac** [jomo/LibreSignal-forever#1]
I have:
- [x] searched open and closed issues for duplicates     0 issues :D
- [ ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

Building fails

### Steps to reproduce

- `bash -x ./gradlew -x lint -x javadoc build` 

**Actual result:** Fails with `Failed to notify ProjectEvaluationListener.afterEvaluate()`
see attached log

**Expected result:** It should build a proprt .apk

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

### Link to debug log

[error.log.txt](https://github.com/jomo/LibreSignal-forever/files/785280/error.log.txt)

**Comment by jomo** [comment]
from your log:
```
* What went wrong:
A problem occurred evaluating root project 'LibreSignal-forever'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
```
